version: "3"
services:

  symfony:

    build:
      context: ./dockerFiles/symfony
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - ./symfonyProject:/my_project_directory
    ports:
      - "8000:8000"
    networks:
      - my-network
    depends_on:
      - composer

  composer:
    image: 'beleguic/composer'
    volumes:
      - ./symfonyProject/:/volume/my_project_directory
    networks:
      - my-network

networks:
  my-network:
