version: "3"
services:
  adminer:
    build: ./dockerFiles/adminer/
    ports:
      - "8080:80"
    depends_on:
      - postgres
  postgres:
    build: ./dockerFiles/postgres/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
#    volumes:
#      - ./data/db:/var/lib/postgresql/
    restart: unless-stopped
  symfony:
    build:
      context: ./dockerFiles/symfony/
      args:
        - PROJECT_NAME=${PROJECT_NAME}
#    volumes:
#      - ./symfony:/var/www/symfony
    depends_on:
      - adminer