version: "3.8"

services:

  adminer:
    build: ./dockerFiles/adminer/
    ports:
      - "8080:80"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - my-network
    depends_on:
      - postgres

  postgres:
    build: ./dockerFiles/postgres/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped

    networks:
      - my-network

networks:
  my-network:
